### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by satrox28** [RahulShaw/LinuxAcademy-DL#11]
:~$ python3.7 driver.py email-id password https://linuxacademy.com/cp/modules/view/id/245
Requesting download of https://linuxacademy.com/cp/modules/view/id/245
Traceback (most recent call last):
  File "driver.py", line 36, in <module>
    options=chrome_options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by ElegantPercentage** [comment]
Were you able to get this resolved? Is this repository still working?

**Comment by mhmdksh** [comment]
I have the same issue, it will open the browser, and it will hang on the sign in page of the Linux Academy website.

**Comment by hyj1116** [comment]
Cannot download file as well.
The error message:

```
  File "driver.py", line 25
    chrome_options.add_argument(f'user-agent={user_agent}')
                                                         ^
SyntaxError: invalid syntax
```

**Comment by pgilmar** [comment]
Pip requirements installed
Cookies file moved to root dir
on Mac

then ran ( python driver.py "username" "password" https://linuxacademy.com/cp/modules/view/id/413 ) 


Installed ffmpeg is still failing any thoughts.


  File "driver.py", line 36
    f'FFmpeg not found. For help, please visit: https://www.google.com/search?q=install%20ffmpeg%20on%20{platform.system()})',
                                                                                                                            ^
SyntaxError: invalid syntax

**Comment by RahulShaw** [comment]
@pgilmar -  Which version of Python are you using?
