### ISSUE TITLE
error selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81

### ISSUE THREAD

**Issue by CarlosJoseChaconChavarria** [RahulShaw/LinuxAcademy-DL#41]
hey guys I am not able to download any help please thanks, see error below thanks

_Executing for https://linuxacademy.com/cp/modules/view/id/392
Traceback (most recent call last):
  File "driver.py", line 68, in <module>
    options=chrome_options)
  File "C:\Users\karlo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\karlo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\karlo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\karlo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\karlo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81_

**Comment by CarlosJoseChaconChavarria** [comment]
**Update:** 
I had to downgrade Chrome from 84 version to 81 and it started downloading
any way to have the latest Chrome version and not affect this script?

thanks

**Comment by RahulShaw** [comment]
Please get the latest ChromeDriver from https://chromedriver.chromium.org/downloads and keep it in sync with your Chrome version
