### ISSUE TITLE
Fails at browser.get(url)

### ISSUE THREAD

**Issue by npsoni88** [RahulShaw/LinuxAcademy-DL#5]
Here is the log output.

```
Requesting download of 327

DevTools listening on ws://127.0.0.1:53902/devtools/browser/d664c427-5b6e-42d4-bd1a-b48615354ff2
Sleeping for 15 seconds..
Attempting to login..
[67724:10928:0509/063124.813:ERROR:ssl_client_socket_impl.cc(962)] handshake failed; returned -1, SSL error code 1, net_error -100
Login successful...
Getting lesson links...
Traceback (most recent call last):
  File "driver.py", line 77, in <module>
    browser.get(url)
  File "C:\Users\Nishant\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Nishant\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Nishant\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot navigate to invalid URL"}
  (Session info: chrome=73.0.3683.103)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17134 x86_64)


D:\LA\LinuxAcademy-DL-master>[67724:10928:0509/063134.831:ERROR:ssl_client_socket_impl.cc(962)] handshake failed; returned -1, SSL error code 1, net_error -100
[67724:10928:0509/063156.751:ERROR:ssl_client_socket_impl.cc(962)] handshake failed; returned -1, SSL error code 1, net_error -100
[67724:10928:0509/063217.434:ERROR:ssl_client_socket_impl.cc(962)] handshake failed; returned -1, SSL error code 1, net_error -100
```

**Comment by RahulShaw** [comment]
You're invoking the script in the wrong manner. Please read the instructions carefully.
For this case please invoke the script like this - python driver.py username password https://linuxacademy.com/cp/modules/view/id/327
