### ISSUE TITLE
Error downloading -   logged_in_name = browser.find_element_by_id('navigationUsername')

### ISSUE THREAD

**Issue by CarlosJoseChaconChavarria** [RahulShaw/LinuxAcademy-DL#54]
hi guys

I've downloaded from LA before but after some months not using this tool I get this error any idea guys

thanks 

Executing for https://linuxacademy.com/cp/modules/view/id/791
* Trying to log in ... *
Traceback (most recent call last):
  File "driver.py", line 88, in <module>
    logged_in_name = browser.find_element_by_id('navigationUsername')
  File "C:\Users\karlo\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\karlo\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\karlo\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\karlo\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="navigationUsername"]"}
  (Session info: headless chrome=89.0.4389.90)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "driver.py", line 92, in <module>
    raise Exception(' ** Failed to log in. Please check your credentials. **')
Exception:  ** Failed to log in. Please check your credentials. **

**Comment by CarlosJoseChaconChavarria** [comment]
latest update (march 2021) fixed the issue, working flawlessly :)

**Comment by RahulShaw** [comment]
@karlochacon - Thanks for the confirmation :)
