### ISSUE TITLE
beutifulsoup error

### ISSUE THREAD

**Issue by npsoni88** [RahulShaw/LinuxAcademy-DL#6]
Here's the log output.

Requesting download of https://linuxacademy.com/cp/modules/view/id/327

```
DevTools listening on ws://127.0.0.1:64833/devtools/browser/fcba1e40-f175-4ca4-a20b-c22e4cb24c5e
Sleeping for 15 seconds..
Attempting to login..
Login successful...
Getting lesson links...
[58884:65544:0509/140806.066:ERROR:ssl_client_socket_impl.cc(962)] handshake failed; returned -1, SSL error code 1, net_error -100
Traceback (most recent call last):
  File "driver.py", line 80, in <module>
    parsed_html = BeautifulSoup(html, 'html5lib')
  File "C:\Users\Nishant\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bs4\__init__.py", line 196, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?
```

**Comment by RahulShaw** [comment]
Please run this - pip install html5lib
